#
# ### Step 1: Build (CI)
#
# Ensure that code successfully builds and builds into a container
#
# Required parameters
# - userName: Registry organization/user prefix
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/vars-all.yaml
- template: vars/vars-ci.yaml

steps:
- template: steps/git-checkout.yaml
#- template: steps/build-test.yaml
- template: steps/publish-deb.yaml
- template: steps/publish-feed.yaml
  parameters: 
    Application: still
#- template: steps/docker-build.yaml
